Cinema/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework.routers import DefaultRouter

from . import views
from .api_views import (
    SubscriptionTypeViewSet,
    SubscriptionViewSet,
    MovieOrderViewSet,
    RestaurantViewSet,
    SnackViewSet,
    SnackOrderViewSet, SubscriptionPaymentViewSet, MovieViewSet, SeatViewSet
)

router = DefaultRouter()
router.register(r'subscriptions/types', SubscriptionTypeViewSet, basename='subscription_type')
router.register(r'subscriptions', SubscriptionViewSet, basename='subscription')
router.register(r'movie', MovieViewSet, basename='movie')
router.register(r'movie-orders', MovieOrderViewSet, basename='movie_order')
router.register(r'restaurants', RestaurantViewSet, basename='restaurant')
router.register(r'snacks', SnackViewSet, basename='snack')
router.register(r'snack-orders', SnackOrderViewSet, basename='snack_order')
router.register(r'subscription/payments', SubscriptionPaymentViewSet, basename='subscription_payment')
router.register(r'seats', SeatViewSet, basename='seat')


urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register_view, name='register'),
    path('forgot-password', views.forgot_password_view, name='forgot_password'),
    path('reset-password', views.password_reset_view, name='password_reset'),
    path('profile', views.profile_view, name='profile'),
    path('transaction', views.transaction_view, name='transaction'),
    path('subscription', views.subscription, name='subscription'),
    path('subscription/<str:subscription_name>', views.change_subscription_view, name='change_subscription'),
    path('home', views.movie_rows, name='home'),
    path('get-available-seats', views.get_available_seats, name='get_available_seats'),
    path('orders', views.get_valid_movie_orders, name='orders'),
    path('movie-detail/<int:movie_id>', views.movie_detail, name='movie_detail'),
    path('download-ticket/<int:order_id>', views.download_ticket, name='download_ticket'),
    path('verify/<str:reference>/', views.verify_payment, name='verify_payment'),
    path('api', include(router.urls)),
]

MovieCinema/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions

from MovieCinema import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Cinema.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cinema/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from decimal import Decimal  # Use Decimal for money fields


class SubscriptionType(models.Model):
    NAME_CHOICES = (
        ('free', 'Free'),
        ('monthly', 'Monthly'),
        ('yearly', 'Yearly'),
    )
    name = models.CharField(max_length=10, choices=NAME_CHOICES, primary_key=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    def __str__(self):
        return self.name


class Subscription(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    subscription_type = models.ForeignKey(SubscriptionType, on_delete=models.CASCADE)
    expiry_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return f'{self.user} - {self.subscription_type} - {self.expiry_date}'

    def is_active(self):
        if self.expiry_date is None:
            return True  # Free subscription is always active
        elif self.expiry_date >= timezone.now().date():
            return True
        else:
            return False

    def add_expiry_date(self):
        """
        Calculates and sets the expiry date based on the provided duration (month or year).
        """
        today = timezone.now().date()
        if self.subscription_type.name == "monthly":
            # Add one month to the current date
            self.expiry_date = today + timezone.timedelta(days=30)  # Adjust for potential month length variations
        elif self.subscription_type.name == "yearly":
            # Add one year to the current date
            self.expiry_date = today + timezone.timedelta(days=365)
        else:
            self.expiry_date = None

        self.save()


class Movie(models.Model):
    external_id = models.CharField(max_length=255, unique=True)
    title = models.CharField(max_length=255)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title


class Restaurant(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Snack(models.Model):
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    image = models.ImageField(upload_to='snack_images/', null=True, blank=True)

    def __str__(self):
        return self.name


class SnackOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    snack = models.ForeignKey(Snack, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    date = models.DateField(default=timezone.now().date())

    def __str__(self):
        return f'{self.user} - {self.snack}'


class SubscriptionPayment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subscription_type = models.ForeignKey(SubscriptionType, on_delete=models.CASCADE)
    date = models.DateField(default=timezone.now().date())

    def __str__(self):
        return f'{self.user} - {self.subscription_type} - {self.subscription_type.price}'


class Seat(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    seat_no = models.IntegerField()
    date = models.DateField()

    def __str__(self):
        return f'{self.user} - {self.seat_no}'


class MovieOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    snacks = models.ManyToManyField(SnackOrder)
    seat = models.ForeignKey(Seat, on_delete=models.CASCADE)
    date = models.DateField(default=timezone.now().date())
    is_used = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user} - {self.movie} - {self.is_used}'

Cinema/views.py
import io
import uuid

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from paystackapi.transaction import Transaction

from Cinema.models import Subscription, SubscriptionType, MovieOrder, Snack, Restaurant, SnackOrder, \
    SubscriptionPayment, Movie, Seat

# Import libraries for API requests and YouTube trailer lookup (replace with your preferred methods)
import requests
from youtubesearchpython import VideosSearch

from PIL import Image, ImageDraw, ImageFont, ImageFilter, ImageOps

# Replace with your actual TMDB API key
API_KEY = '1e28d26c788dd3b0a958103a97804da4'
base_url = "https://image.tmdb.org/t/p/original"


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            subscript = Subscription.objects.get(user=user)
            if not subscript.is_active():
                subscript.subscription_type = SubscriptionType.objects.get(name='free')
                subscript.add_expiry_date()
                subscript.save()
            # Redirect to successful login page
            return redirect('home')  # Replace 'home' with your desired redirect URL
        else:
            # Invalid login credentials
            messages.error(request, 'Invalid username or password.')
            return render(request, 'login.html')
    return render(request, 'login.html')


def register_view(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        if password1 != password2:
            messages.error(request, 'Passwords do not match.')
            return render(request, 'register.html')
        # Create user
        user = User.objects.create_user(first_name=first_name, last_name=last_name, username=username, email=email,
                                        password=password1)
        user.save()
        subscription_type = SubscriptionType.objects.get(name='free')
        Subscription.objects.get_or_create(user=user, subscription_type=subscription_type)
        messages.success(request, 'Your account has been successfully created.')
        return redirect('login')  # Replace 'home' with your desired redirect URL
    return render(request, 'register.html')


def forgot_password_view(request):
    if request.method == 'POST':
        email = request.POST['email'].strip()
        try:
            user = User.objects.get(email=email)
            login(request, user)
            return redirect('password_reset')
        except User.DoesNotExist:
            messages.error(request, 'Email address not found.')
            return redirect('forgot_password')
    return render(request, 'forgot_password.html')


def password_reset_view(request):
    user = request.user

    if request.method == 'POST':
        new_password1 = request.POST['new_password1'].strip()
        new_password2 = request.POST['new_password2'].strip()
        if new_password1 != new_password2:
            messages.error(request, 'Passwords do not match.')
            return redirect('password_reset')
        # Set the new password
        user.set_password(new_password1)
        user.save()
        logout(request)
        messages.success(request, 'Password reset successfully!')
        return redirect('login')
    return render(request, 'password_reset.html')


@login_required
def logout_view(request):
    logout(request)
    return redirect('login')


@login_required
def profile_view(request):
    user = request.user
    subscript = Subscription.objects.get(user=user)

    if request.method == 'POST':
        current_password = request.POST['current_password']
        new_password1 = request.POST['new_password1']
        new_password2 = request.POST['new_password2']

        user = authenticate(request, username=request.user.username, password=current_password)
        if user is not None:
            if new_password1 != new_password2:
                messages.error(request, 'New passwords do not match.')
            else:
                user.set_password(new_password1)
                user.save()
                messages.success(request, 'Password changed successfully!')
                return redirect('profile')
        else:
            messages.error(request, 'Invalid current password.')
            return redirect('profile')

    context = {
        'user': user,
        'subscription': subscript.subscription_type,
    }
    return render(request, 'profile.html', context)


@login_required
def subscription(request):
    subscript = Subscription.objects.get(user=request.user)

    return render(request, 'subscription.html', {'subscription': subscript.subscription_type})


@login_required
def change_subscription_view(request, subscription_name):
    try:
        selected_type = SubscriptionType.objects.get(name=subscription_name)

        if selected_type.name != 'free':
            response = Transaction.initialize(
                reference=str(uuid.uuid4()),
                amount=float(selected_type.price) * 100,
                email=request.user.email
            )

            user_subscription = Subscription.objects.get(user=request.user)
            user_subscription.subscription_type = selected_type
            user_subscription.add_expiry_date()
            user_subscription.save()

            SubscriptionPayment.objects.create(user=request.user, subscription_type=selected_type)
            messages.success(request, 'Subscription update successful.')
            return HttpResponseRedirect(response['data']['authorization_url'])
        else:
            user_subscription = Subscription.objects.get(user=request.user)
            user_subscription.subscription_type = selected_type
            user_subscription.add_expiry_date()
            user_subscription.save()
            messages.success(request, 'Subscription update successful.')
            return redirect('subscription')
    except SubscriptionType.DoesNotExist:
        messages.error(request, 'Invalid subscription type selected.')
        return redirect('subscription')


@login_required
def movie_rows(request):
    """
  Fetches data for movie rows and handles trailer lookup.

  Renders a template with movie data and potential trailer URLs.
  """
    selected_type = Subscription.objects.get(user=request.user).subscription_type

    if selected_type.name != 'free':
        fetch_urls = {
            'trending': f'/trending/all/week?api_key={API_KEY}&language=en-US',
            'netflix_originals': f'/discover/tv?api_key={API_KEY}&with_networks=213',
            'top_rated': f'/movie/top_rated?api_key={API_KEY}&language=en-US',
            'top_action': f'/discover/movie?api_key={API_KEY}&with_genres=28',
            # 'top_comedy': f'/discover/movie?api_key={API_KEY}&with_genres=35',
            # 'top_horror': f'/discover/movie?api_KEY={API_KEY}&with_genres=27',
            # 'top_romance': f'/discover/movie?api_KEY={API_KEY}&with_genres=10749',
            # 'top_documentaries': f'/discover/movie?api_KEY={API_KEY}&with_genres=99',
        }

        movie_data = {}
        for category, url in fetch_urls.items():
            movies = []
            try:
                response = requests.get(f'https://api.themoviedb.org/3{url}')
                response.raise_for_status()  # Raise an exception for failed requests
                movies = response.json()['results']
            except requests.exceptions.RequestException as e:
                print(f"Error fetching data for {category}: {e}")

            movie_data[category] = {
                'movies': movies,
            }
        context = {
            'trending': movie_data['trending']['movies'],
            'netflix_originals': movie_data['netflix_originals']['movies'],
            'top_rated': movie_data['top_rated']['movies'],
            'top_action': movie_data['top_action']['movies'],
            'base_url': base_url,
        }

    else:
        fetch_urls = {
            'trending': f'/trending/all/week?api_key={API_KEY}&language=en-US',
        }

        movie_data = {}
        for category, url in fetch_urls.items():
            movies = []
            try:
                response = requests.get(f'https://api.themoviedb.org/3{url}')
                response.raise_for_status()  # Raise an exception for failed requests
                movies = response.json()['results']
            except requests.exceptions.RequestException as e:
                print(f"Error fetching data for {category}: {e}")

            movie_data[category] = {
                'movies': movies,
            }

        context = {
            'trending': movie_data['trending']['movies'],
            'base_url': base_url,
        }
    return render(request, 'home.html', context)


@login_required
def movie_detail(request, movie_id):
    """
    Fetches details for a specific movie using its ID.

    Renders a template with the movie details.
    """

    user = request.user

    try:
        url = f'https://api.themoviedb.org/3/movie/{movie_id}?api_key={API_KEY}&language=en-US'
        response = requests.get(url)
        response.raise_for_status()  # Raise an exception for failed requests
        movie_data = response.json()
    except requests.exceptions.RequestException as e:
        messages.error(request, f"Error fetching movie details for ID {movie_id}: {e}")

Cinema/templates/card.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Movie Ticket</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      font-family: sans-serif;
      background-color: #222;  /* Black background */
    }

    .ticket {
      width: 400px;
      height: 200px;
      margin: 50px auto;
      background-color: #fff;
      border-radius: 20px;
      box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
      padding: 20px;
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      align-items: center;
      color: #333;  /* Text color */
    }

    .company-name {
      display: flex;
      justify-content: center;
      align-items: center;
      gap: 5px;
    }

    .company-name h2:first-child {
      color: #000;  /* Black for MOVIE */
    }

    .company-name h2:last-child {
      color: #f05040;  /* Red for CINEMA */
    }

    .user-info {
      text-align: center;
    }

    h2 {
      margin: 0;
      font-size: 20px;
    }

    .seat,
    .date {
      font-weight: bold;
    }
  </style>
</head>
<body>
  <div class="ticket">
    <div class="company-name">
      <h2>MOVIE</h2>
      <h2>CINEMA</h2>
    </div>
    <div class="user-info">
      <h2>{{ order.user.first_name }} {{ order.user.last_name }}</h2>
    </div>
    <h2>{{ order.movie.title }}</h2>
    <div class="details">
      <p class="seat">Seat NO. {{ order.seat.seat_no }}</p>
      <p class="date">{{ order.date }}</p>
    </div>
  </div>
</body>
</html>

Cinema/templates/forgot_password.html
{% extends 'auth.html' %}

{% load static %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <div id="toast">
        {% for message in messages %}
        <div class="alert alert-info" role="alert"><strong></strong><i>{{ message }}</i></div>
        {% endfor %}
    </div>
    <div class="mb-3">
        <label class="text-white fw-500 mb-2">Email Address</label>
        <input type="text" name="email" class="form-control rounded-0" required="">
    </div>
    <div class="full-button">
        <div class="iq-button">
            <button type="submit" class="btn text-uppercase position-relative">
                <span class="button-text">submit</span>
                <i class="fa-solid fa-play"></i>
            </button>
        </div>
    </div>
</form>
{% endblock content %}

Cinema/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Movies{% endblock title %}

{% block subtitle %}Movies{% endblock subtitle %}

{% block main %}
<div class="section-padding">
    <div class="container-fluid">
        {% if trending %}
        <div class="d-flex align-items-center justify-content-between mb-4">
            <h4 class="main-title text-capitalize mb-0">Trending</h4>
        </div>

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
            {% for movie in trending %}
            <div class="col mb-4">
                <div class="iq-card-geners card-hover-style-two">
                    <div class="block-images position-relative w-100">
                        <a href="{% url 'movie_detail' movie.id %}">
                            <div class="img-box rounded position-relative">
                                <img src="{{ base_url }}{{ movie.backdrop_path }}" alt="geners-img"
                                     class="img-fluid object-cover w-100 rounded">
                                <div class="blog-description">
                                    <h6 class="mb-0 iq-title">
                                        {% if movie.title %}
                                        {{ movie.title }}
                                        {% elif movie.original_title %}
                                        {{ movie.original_title }}
                                        {% elif movie.original_name %}
                                        {{ movie.original_name }}
                                        {% elif movie.name %}
                                        {{ movie.name }}
                                        {% endif %}
                                    </h6>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}

        {% if netflix_originals %}
        <div class="d-flex align-items-center justify-content-between my-4">
            <h4 class="main-title text-capitalize mb-0">Netflix Originals</h4>
        </div>

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
            {% for movie in netflix_originals %}
            <div class="col mb-4">
                <div class="iq-card-geners card-hover-style-two">
                    <div class="block-images position-relative w-100">
                        <a href="{% url 'movie_detail' movie.id %}">
                            <div class="img-box rounded position-relative">
                                <img src="{{ base_url }}{{ movie.backdrop_path }}" alt="geners-img"
                                     class="img-fluid object-cover w-100 rounded">
                                <div class="blog-description">
                                    <h6 class="mb-0 iq-title">
                                        {% if movie.title %}
                                        {{ movie.title }}
                                        {% elif movie.original_title %}
                                        {{ movie.original_title }}
                                        {% elif movie.original_name %}
                                        {{ movie.original_name }}
                                        {% elif movie.name %}
                                        {{ movie.name }}
                                        {% endif %}
                                    </h6>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}

        {% if top_rated %}
        <div class="d-flex align-items-center justify-content-between my-4">
            <h4 class="main-title text-capitalize mb-0">Top Rated</h4>
        </div>

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
            {% for movie in top_rated %}
            <div class="col mb-4">
                <div class="iq-card-geners card-hover-style-two">
                    <div class="block-images position-relative w-100">
                        <a href="{% url 'movie_detail' movie.id %}">
                            <div class="img-box rounded position-relative">
                                <img src="{{ base_url }}{{ movie.backdrop_path }}" alt="geners-img"
                                     class="img-fluid object-cover w-100 rounded">
                                <div class="blog-description">
                                    <h6 class="mb-0 iq-title">
                                        {% if movie.title %}
                                        {{ movie.title }}
                                        {% elif movie.original_title %}
                                        {{ movie.original_title }}
                                        {% elif movie.original_name %}
                                        {{ movie.original_name }}
                                        {% elif movie.name %}
                                        {{ movie.name }}
                                        {% endif %}
                                    </h6>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}

        {% if top_action %}
        <div class="d-flex align-items-center justify-content-between my-4">
            <h4 class="main-title text-capitalize mb-0">Top Action</h4>
        </div>

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
            {% for movie in top_action %}
            <div class="col mb-4">
                <div class="iq-card-geners card-hover-style-two">
                    <div class="block-images position-relative w-100">
                        <a href="{% url 'movie_detail' movie.id %}">
                            <div class="img-box rounded position-relative">
                                <img src="{{ base_url }}{{ movie.backdrop_path }}" alt="geners-img"
                                     class="img-fluid object-cover w-100 rounded">
                                <div class="blog-description">
                                    <h6 class="mb-0 iq-title">
                                        {% if movie.title %}
                                        {{ movie.title }}
                                        {% elif movie.original_title %}
                                        {{ movie.original_title }}
                                        {% elif movie.original_name %}
                                        {{ movie.original_name }}
                                        {% elif movie.name %}
                                        {{ movie.name }}
                                        {% endif %}
                                    </h6>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>
{% endblock main %}

Cinema/templates/login.html
{% extends 'auth.html' %}

{% load static %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <div id="toast">
        {% for message in messages %}
        <div class="alert alert-info" role="alert"><strong></strong><i>{{ message }}</i></div>
        {% endfor %}
    </div>
    <div class="mb-3">
        <label class="text-white fw-500 mb-2">Username</label>
        <input type="text" name="username" class="form-control rounded-0" required="">
    </div>
    <div class="mb-3">
        <label class="text-white fw-500 mb-2">Password</label>
        <input type="password" name="password" class="form-control rounded-0" required="">
    </div>
    <div class="text-end mb-3">
        <a href="{% url 'forgot_password' %}" class="text-primary fw-semibold fst-italic">Forgot
            Password?</a>
    </div>
    <div class="full-button">
        <div class="iq-button">
            <button type="submit" class="btn text-uppercase position-relative">
                <span class="button-text">log in</span>
                <i class="fa-solid fa-play"></i>
            </button>
        </div>
    </div>
</form>
<p class="my-4 text-center fw-500 text-white">New to Movie Cinema? <a href="{% url 'register' %}"
                                                                      class="text-primary ms-1">Register</a>
</p>
{% endblock content %}

Cinema/templates/movie_order.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Orders{% endblock title %}

{% block subtitle %}Orders{% endblock subtitle %}

{% block main %}

<div class="section-padding">
    <div class="container">
        <div class="order">
            <p class="thank">VALID MOVIE ORDERS</p>
            <table class="table">
                <thead>
                    <tr>
                        <th>Movie Title</th>
                        <th>Seat No</th>
                        <th>Snacks</th>
                        <th>Date</th>
                        <th>Download Ticket</th>
                    </tr>
                </thead>
                <tbody>
                    {% if movie_orders %}
                        {% for order in movie_orders %}
                            <tr>
                                <td>{{ order.movie.title }}</td>
                                <td>{{ order.seat.seat_no }}</td>
                                <td>
                                    <ul>
                                        {% for snack_order in order.snack_set.all %}
                                            <li>{{ snack_order.snack.name }}</li>
                                        {% endfor %}
                                    </ul>
                                </td>
                                <td>{{ order.date }}</td>
                                <td>
                                    <a class="full-button" href="{% url 'download_ticket' order.id %}">
                                        <div class="iq-button">
                                            <button type="submit" id="btn"
                                                    class="btn text-uppercase position-relative">
                                                <span class="button-text">Download</span>
                                                <i class="fa-solid fa-download"></i>
                                            </button>
                                        </div>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="5">No available movie orders</td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock main %}

Cinema/templates/password_reset.html
{% extends 'auth.html' %}

{% load static %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <div id="toast">
        {% for message in messages %}
        <div class="alert alert-info" role="alert"><strong></strong><i>{{ message }}</i></div>
        {% endfor %}
    </div>
    <div class="mb-3">
        <label class="text-white fw-500 mb-2">Password</label>
        <input type="password" name="new_password1" class="form-control rounded-0" required="">
    </div>
    <div class="mb-3">
        <label class="text-white fw-500 mb-2">Confirm Password</label>
        <input type="password" name="new_password2" class="form-control rounded-0" required="">
    </div>
    <div class="full-button">
        <div class="iq-button">
            <button type="submit" class="btn text-uppercase position-relative">
                <span class="button-text">submit</span>
                <i class="fa-solid fa-play"></i>
            </button>
        </div>
    </div>
</form>
{% endblock content %}